### ISSUE TITLE
When will this be updated to latest version?

### ISSUE THREAD

**Issue by LiquidLemming** [flathub/org.twinery.Twine#4]
The flathub build is still 2.3.16, released over 10 months ago, while the current version is 2.5.1 (released August 2022).

The newer version brings a bunch of awesome features, including a brand new writing GUI.

**Comment by SISheogorath** [comment]
After making another effort to update tonight, I remembered why: I'm currently unable to create new builds until we get screenshots. Since I have no time to do this at hand, this is left as an exercise to those who want a new build: https://github.com/flathub/org.twinery.Twine/pull/5

You can build it locally using `flatpak-builder builddir --install-deps-from=flathub org.twinery.Twine.yaml` or ask upstream to provide screenshots.

**Comment by SISheogorath** [comment]
Solved by #7
